__author__ = 'hang'

teams = {'MIL': {'conference': 'Eastern', 'city': 'Milwaukee', 'code': 'bucks', 'displayAbbr': 'MIL', 'abbr': 'MIL',
                 'division': 'Central', 'displayConference': 'Eastern', 'id': '1610612749', 'name': 'Bucks'},
         'GSW': {'conference': 'Western', 'city': 'Golden State', 'code': 'warriors', 'displayAbbr': 'GSW',
                 'abbr': 'GSW', 'division': 'Pacific', 'displayConference': 'Western', 'id': '1610612744',
                 'name': 'Warriors'},
         'MIN': {'conference': 'Western', 'city': 'Minnesota', 'code': 'timberwolves', 'displayAbbr': 'MIN',
                 'abbr': 'MIN', 'division': 'Northwest', 'displayConference': 'Western', 'id': '1610612750',
                 'name': 'Timberwolves'},
         'MIA': {'conference': 'Eastern', 'city': 'Miami', 'code': 'heat', 'displayAbbr': 'MIA', 'abbr': 'MIA',
                 'division': 'Southeast', 'displayConference': 'Eastern', 'id': '1610612748', 'name': 'Heat'},
         'ATL': {'conference': 'Eastern', 'city': 'Atlanta', 'code': 'hawks', 'displayAbbr': 'ATL', 'abbr': 'ATL',
                 'division': 'Southeast', 'displayConference': 'Eastern', 'id': '1610612737', 'name': 'Hawks'},
         'BOS': {'conference': 'Eastern', 'city': 'Boston', 'code': 'celtics', 'displayAbbr': 'BOS', 'abbr': 'BOS',
                 'division': 'Atlantic', 'displayConference': 'Eastern', 'id': '1610612738', 'name': 'Celtics'},
         'DET': {'conference': 'Eastern', 'city': 'Detroit', 'code': 'pistons', 'displayAbbr': 'DET', 'abbr': 'DET',
                 'division': 'Central', 'displayConference': 'Eastern', 'id': '1610612765', 'name': 'Pistons'},
         'NYK': {'conference': 'Eastern', 'city': 'New York', 'code': 'knicks', 'displayAbbr': 'NYK', 'abbr': 'NYK',
                 'division': 'Atlantic', 'displayConference': 'Eastern', 'id': '1610612752', 'name': 'Knicks'},
         'DEN': {'conference': 'Western', 'city': 'Denver', 'code': 'nuggets', 'displayAbbr': 'DEN', 'abbr': 'DEN',
                 'division': 'Northwest', 'displayConference': 'Western', 'id': '1610612743', 'name': 'Nuggets'},
         'DAL': {'conference': 'Western', 'city': 'Dallas', 'code': 'mavericks', 'displayAbbr': 'DAL', 'abbr': 'DAL',
                 'division': 'Southwest', 'displayConference': 'Western', 'id': '1610612742', 'name': 'Mavericks'},
         'BKN': {'conference': 'Eastern', 'city': 'Brooklyn', 'code': 'nets', 'displayAbbr': 'BKN', 'abbr': 'BKN',
                 'division': 'Atlantic', 'displayConference': 'Eastern', 'id': '1610612751', 'name': 'Nets'},
         'POR': {'conference': 'Western', 'city': 'Portland', 'code': 'blazers', 'displayAbbr': 'POR', 'abbr': 'POR',
                 'division': 'Northwest', 'displayConference': 'Western', 'id': '1610612757', 'name': 'Trail Blazers'},
         'OKC': {'conference': 'Western', 'city': 'Oklahoma City', 'code': 'thunder', 'displayAbbr': 'OKC',
                 'abbr': 'OKC', 'division': 'Northwest', 'displayConference': 'Western', 'id': '1610612760',
                 'name': 'Thunder'},
         'TOR': {'conference': 'Eastern', 'city': 'Toronto', 'code': 'raptors', 'displayAbbr': 'TOR', 'abbr': 'TOR',
                 'division': 'Atlantic', 'displayConference': 'Eastern', 'id': '1610612761', 'name': 'Raptors'},
         'CHI': {'conference': 'Eastern', 'city': 'Chicago', 'code': 'bulls', 'displayAbbr': 'CHI', 'abbr': 'CHI',
                 'division': 'Central', 'displayConference': 'Eastern', 'id': '1610612741', 'name': 'Bulls'},
         'SAS': {'conference': 'Western', 'city': 'San Antonio', 'code': 'spurs', 'displayAbbr': 'SAS', 'abbr': 'SAS',
                 'division': 'Southwest', 'displayConference': 'Western', 'id': '1610612759', 'name': 'Spurs'},
         'CHA': {'conference': 'Eastern', 'city': 'Charlotte', 'code': 'hornets', 'displayAbbr': 'CHA', 'abbr': 'CHA',
                 'division': 'Southeast', 'displayConference': 'Eastern', 'id': '1610612766', 'name': 'Hornets'},
         'UTA': {'conference': 'Western', 'city': 'Utah', 'code': 'jazz', 'displayAbbr': 'UTA', 'abbr': 'UTA',
                 'division': 'Northwest', 'displayConference': 'Western', 'id': '1610612762', 'name': 'Jazz'},
         'CLE': {'conference': 'Eastern', 'city': 'Cleveland', 'code': 'cavaliers', 'displayAbbr': 'CLE', 'abbr': 'CLE',
                 'division': 'Central', 'displayConference': 'Eastern', 'id': '1610612739', 'name': 'Cavaliers'},
         'HOU': {'conference': 'Western', 'city': 'Houston', 'code': 'rockets', 'displayAbbr': 'HOU', 'abbr': 'HOU',
                 'division': 'Southwest', 'displayConference': 'Western', 'id': '1610612745', 'name': 'Rockets'},
         'WAS': {'conference': 'Eastern', 'city': 'Washington', 'code': 'wizards', 'displayAbbr': 'WAS', 'abbr': 'WAS',
                 'division': 'Southeast', 'displayConference': 'Eastern', 'id': '1610612764', 'name': 'Wizards'},
         'LAL': {'conference': 'Western', 'city': 'Los Angeles', 'code': 'lakers', 'displayAbbr': 'LAL', 'abbr': 'LAL',
                 'division': 'Pacific', 'displayConference': 'Western', 'id': '1610612747', 'name': 'Lakers'},
         'PHI': {'conference': 'Eastern', 'city': 'Philadelphia', 'code': 'sixers', 'displayAbbr': 'PHI', 'abbr': 'PHI',
                 'division': 'Atlantic', 'displayConference': 'Eastern', 'id': '1610612755', 'name': 'Sixers'},
         'MEM': {'conference': 'Western', 'city': 'Memphis', 'code': 'grizzlies', 'displayAbbr': 'MEM', 'abbr': 'MEM',
                 'division': 'Southwest', 'displayConference': 'Western', 'id': '1610612763', 'name': 'Grizzlies'},
         'LAC': {'conference': 'Western', 'city': 'Los Angeles', 'code': 'clippers', 'displayAbbr': 'LAC',
                 'abbr': 'LAC', 'division': 'Pacific', 'displayConference': 'Western', 'id': '1610612746',
                 'name': 'Clippers'},
         'SAC': {'conference': 'Western', 'city': 'Sacramento', 'code': 'kings', 'displayAbbr': 'SAC', 'abbr': 'SAC',
                 'division': 'Pacific', 'displayConference': 'Western', 'id': '1610612758', 'name': 'Kings'},
         'ORL': {'conference': 'Eastern', 'city': 'Orlando', 'code': 'magic', 'displayAbbr': 'ORL', 'abbr': 'ORL',
                 'division': 'Southeast', 'displayConference': 'Eastern', 'id': '1610612753', 'name': 'Magic'},
         'PHX': {'conference': 'Western', 'city': 'Phoenix', 'code': 'suns', 'displayAbbr': 'PHX', 'abbr': 'PHX',
                 'division': 'Pacific', 'displayConference': 'Western', 'id': '1610612756', 'name': 'Suns'},
         'IND': {'conference': 'Eastern', 'city': 'Indiana', 'code': 'pacers', 'displayAbbr': 'IND', 'abbr': 'IND',
                 'division': 'Central', 'displayConference': 'Eastern', 'id': '1610612754', 'name': 'Pacers'},
         'NOP': {'conference': 'Western', 'city': 'New Orleans', 'code': 'pelicans', 'displayAbbr': 'NOP',
                 'abbr': 'NOP', 'division': 'Southwest', 'displayConference': 'Western', 'id': '1610612740',
                 'name': 'Pelicans'}}